### ISSUE TITLE
Gulp Build Script

### ISSUE THREAD

**Issue by gregfrasco** [hicsail/anchor#108]
Build a Gulp Script that cp asset files into the correct public directory
Bootstrap.js and js dependencies
Bootstrap.css
JQuery
Moment.js
Select2.css and js
Datatables css and js including bootstrap css
joi-browser
chart.js

[Sample Gulp Here](https://gist.github.com/gregfrasco/02218f4a9122a48f8b3a2c544ec0a30b)

**Comment by SarahL88** [comment]
Pushed **gulpfile.js** and updated **package.json** to new branch "issue108".
