### ISSUE TITLE
Anchor - API

### ISSUE THREAD

**Issue by gregfrasco** [hicsail/anchor#116]
https://github.com/hicsail/anchor/blob/AnchorModel/server/api/anchor-api.js

Create routes 
 - [x] Create - `POST /api/{collectionName}`
 - [x] Get - `GET /api/{collectionName}`

Route Should
- [x] Find Model using `server.plugin['hapi-anchor-model']['models'][collectionName]`
- [x] See if Model is enabled. Create a object in Model. 
```
User.routes = {
   create: {
    disabled: false
};
```
- [x] Add Handler

**Comment by FrancisZamora** [comment]
closing in #125
