### ISSUE TITLE
Model Testing

### ISSUE THREAD

**Issue by gregfrasco** [hicsail/anchor#126]
Test Some models
First Need to have some fixtures
- [x]  create a fixtures db /test/server/fixtures/db.js [example](https://github.com/jedireza/frame/blob/master/test/server/fixtures/db.js) Update our with our models
- [x] create tests for analytics [example](https://github.com/jedireza/frame/blob/master/test/server/models/status.js)
- [x] create tests for backups
- [x] create tests for feedback
- [x] create tests for invite
- [x] create auth attempts, sesssion, token and user
- [x] create tests for notification

**Comment by FrancisZamora** [comment]
Greg, I can work on the rest of the tests
