### ISSUE TITLE
Anchor Auth Basic

### ISSUE THREAD

**Issue by gregfrasco** [hicsail/anchor#127]
[Example File](https://github.com/jedireza/frame/blob/master/server/auth.js)

- [x] install hapi-auth-basic plugin, add to manifest
- [x] create `./server/auth.js`
- [x] On Line 9 make a function called validate able to be called externally, we will use this method to validate the session in the anchor API.
- [x] return credentials object with user and session, we will have our own scope and roles in the future (Line 29 - 37)

**Comment by FrancisZamora** [comment]
Closing in #143
