### ISSUE TITLE
Anchor API Auth

### ISSUE THREAD

**Issue by gregfrasco** [hicsail/anchor#150]
Add Authentication Checks into Pre Routes.

Should check authentication with basic and session if Model.routes[route].auth is equal to true

Pre Methods
- [x] `authEnabled` - is auth enabled
- [x] `simple` - simple auth test runs in parallel with other auth tests. Return creds or null - doesn't throw an error
- [x] `session` - session auth test runs in parallel with other auth tests. Return creds or null - doesn't throw an error
- [x] `credentials` - check if any auth pres is valid and returns a creds object (user and session) or throws error if all failed 401 unauthicated

**Comment by FrancisZamora** [comment]
Closing in #157
