### ISSUE TITLE
Anchor Token Auth

### ISSUE THREAD

**Issue by gregfrasco** [hicsail/anchor#158]
- [x] use [hapi-auth-jwt2](https://github.com/dwyl/hapi-auth-jwt2) as an auth strategy 
- [x] check vaild token. Check first 12 bytes for id. Token.FindByID, then do crypto.compare() to see if token is vaild
- [x] return `creds`  `{user: userObject, session: Token}`

**Comment by FrancisZamora** [comment]
Closing in #169
