### ISSUE TITLE
User's Permission

### ISSUE THREAD

**Issue by gregfrasco** [hicsail/anchor#176]
## permission(user) 
- [x] create a function named permissions in auth.js that takes in the current users object.
permission(user) 
  - [x] get all roles the user currently has
  - [x] build a permission object with the current user's permissions
    - [x] loop though the user's role permissions and merge the permission.
       - if permission is false in 1st role, and false in 2nd role then permission is false
       - if permission is true in 1st role, and false in 2nd role then permission is true
       - if permission is true in 1st role, and true in 2nd role then permission is true
    - [x] merge user's permission object `user.permissions` with the combined permission object
    - [x] return permission object
## auth
- [x] in the auth strategies call permission(user) 
- [x] check if the user has the correct permission
  - [x] if user doesnt have correct permission `throw Boom.forbidden('Need permission')`

## info
permission object keys
```js
{
   "POST-api-users": true // translates into `POST /api/users`
}
```

**Comment by FrancisZamora** [comment]
Closing in #179
