### ISSUE TITLE
Auth-Attempts Timeout

### ISSUE THREAD

**Issue by gregfrasco** [hicsail/anchor#181]
- [x] Modify the abuseDetected function in auth-attempts to count within a certain time period.
- [x] Use Config.get('/authAttempts/hours'); to get the number of hours the account will be locked for.
- [x] Add hours to authAttempts in config.js
```js
authAttempts: {
    forIp: 50,
    forIpAndUser: 7,
    hours: 1
  }
```

**Comment by FrancisZamora** [comment]
Closing in #186
